version: '3'

services:
  backendserver:
    build: ./taxes-backend/
    ports:
      - "8081"
    restart: always

  frontend:
    build: ./taxes-ui/
    links:
      - "backendserver"
    depends_on:
      - "backendserver"
    ports:
    - "80:80"