version: '3'

services:
  backendserver:
    build: ./taxes-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./taxes-ui
    links:
      - "backendserver"
    depends_on:
      - "backendserver"
    ports:
    - "4200:4200"